### ISSUE TITLE
مشکل نمایش آی پی برای عملیات های دیگر

### ISSUE THREAD

**Issue by AkbarAsghari** [NoobforAl/DnsLab#1]
مثال برای نمونه وقتی op برای بررسی پورت استفاده میشود اول آی پی نمایش داده میشود که این کار اضافه میباشد و باعث سر در گمی میشود 
![2022-11-21](https://user-images.githubusercontent.com/36479679/202928071-46b7ce1c-e094-4a81-af5e-96e30fbe30cf.png)

**Comment by NoobforAl** [comment]
فیکس شد!
[](url)https://github.com/NoobforAl/DnsLab-CLI/commit/5a04a1be76afb2a29e9d363fdc59612d62924c12

**Comment by AkbarAsghari** [comment]
بررسی میکنم و حتما روی داکیومنت سایت قرار میدم ❤️
ممنون از پیگیری شما
