### ISSUE TITLE
تغییر نام متد

### ISSUE THREAD

**Issue by AkbarAsghari** [NoobforAl/DnsLab#3]
سلام 
متد دریافت پینگ رو تغییر نام دادیم اگه وقت داشتید اعمال کنید . 
تغییر نام از IPHavePing به Ping  
و خورجی آن بجای Bool به Json زیر تغییر یافته است .

`{"bufferSize":int,"ip":"string","ttl":int,"time":long,"success":bool}`

برای مثال 

`{"bufferSize":32,"ip":"151.242.106.126","ttl":20,"time":11,"success":true}`

آدرس جدید بصورت زیر میباشد 

[api.dnslab.ir/ip/ping](https://api.dnslab.ir/IP/Ping?hostOrIPAddress=google.com)

**Comment by NoobforAl** [comment]
سلام 
بله حتما 
api تغیرات دیگه ای هم داشته ؟؟

**Comment by AkbarAsghari** [comment]
سلام بله خیلی زیاد :)
چند تا متد جدید اضافه شده و یک تغییر مسیر در جستجوی معکوس
https://dnslab.ir/api
بنظرم یه بار دیگه صفحه API ها رو بررسی کنید و هر وقت راحت بودید و وقت اضافه داشتید اقدام به پیاده سازی کنید . 
کمگ هم خواستید بفرمایید در خدمتم .

**Comment by AkbarAsghari** [comment]
راستی اگه تونستی یه سر به منوی ابزار ها بزن اونجا خروجی رو ببین و ایده بگیر یا اگه کم و کسری داره بگو درست کنم 
مثلا برای Ping گرفتن 4 بار بصورت 700 میلی ثانیه تاخیر متد رو صدا بزنی بهتره تا 4 بار Ping بگیره از سرور

**Comment by NoobforAl** [comment]
اوکی حتما
انگار باید ورژن برنامه رو ببرم بالا !
الان تغیرات stable هستند ؟ 
یا ممکنه تغیر کنن ؟

**Comment by AkbarAsghari** [comment]
فعلا پایدار هستش ولی یک ماه دیگه متد DNSLookUp/Query یک ورودی جدید به اسم DNSServer اضافه میشه بهش

**Comment by NoobforAl** [comment]
Done!
